import { simpsonsQuoteTest, simpsonsQuoteTest1, simpsonsQuoteTest2 } from './simpsonsQuoteData';

describe('Gameplay flow', ()=> {
    it('Should be able to go through a game of Who Said It?, rendering correct elements, and add a point to Woohoo!', () => {
        cy.intercept('GET', 'https://thesimpsonsquoteapi.glitch.me/quotes', simpsonsQuoteTest)
        cy.visit('http://localhost:3000/home')
        .contains('Who Said It?')
                .get('img')
                    .should('have.class', 'App-logo')
                .get('nav')
                    .should('have.class', 'navbar')
                    .contains('Woohoo: 0')
                .get('h2')
                    .contains("D'oh: 0")
                .get('h2')
                    .contains('Fav Quotes')
                .get('section')
                    .should('have.class','quote-body')
                .get('div')
                    .should('have.class', 'quote')
                .get('div')
                    .should('have.class', 'top-corner')
                .get('p')
                    .contains("For once maybe someone will call me \"sir\" without adding, \"You're making a scene.\"")
                .get('button')
                    .should('have.class', 'quote-button')
                .get('p')
                    .contains('Click when you know')
                .get('p')
                    .contains('Who Said It')
                .get('img')
                    .should('have.class', 'simpsons-family')
        cy.get('.quote-button').click()
            .get('div')
                .should('have.class', 'character-name')
            .get('p')
                .contains("It's Homer Simpson!")
            .get('img')
                .should('have.class', 'simpsons-character')
            .get('p')
                .should('have.class', 'guess')
                .contains('Is this who you guessed?')
            .get('button')
                .should('have.class', 'woohoo-button')
                .contains('Woohoo!')
            .get('button')
                .should('have.class', 'doh-button')
                .contains("D'oh!")
        cy.get('.woohoo-button').click()
        cy.visit('http://localhost:3000/woohoo')
            .get('div')
                .should('have.class', 'woohoo-heading')
            .get('h3')
                .contains('Woohoo!')
            .get('h3')
                .contains('+1')
            .get('button')
                .should('have.class', 'play-again-container')
                .contains('Play again!')
        cy.get('button').click()
            .get('h2')
                .contains('Woohoo: 1')
    })
    it("Should be able to go through a game of Who Said It? and add a point to D'oh!", () => {
        cy.intercept('GET', 'https://thesimpsonsquoteapi.glitch.me/quotes', simpsonsQuoteTest1)
        cy.visit('http://localhost:3000/home')
        cy.get('.quote-button').click()
            .get('div')
                .should('have.class', 'character-name')
            .get('p')
                .contains("It's Chief Wiggum!")
        cy.get('.doh-button').click()
        cy.visit('http://localhost:3000/doh')
            .get('div')
                .should('have.class', 'doh-heading')
            .get('h3')
                .contains("D'oh!")
            .get('h3')
                .contains('+1')
        cy.get('button').click()
            .get('h2')
                .contains("D'oh: 1")
    })
    it('Should display error handling during game play if something happens', () => {
        cy.intercept('GET', 'https://thesimpsonsquoteapi.glitch.me/quotes', simpsonsQuoteTest2)
        cy.visit('http://localhost:3000/home')
        cy.get('.quote-button').click()
        cy.intercept('GET', 'https://thesimpsonsquoteapi.glitch.me/quotes', {forceNetworkError: true})
        cy.visit('http://localhost:3000/home')
            .get('section')
                .should('have.class','quote-body')
                .contains('Loading...')
            .get('div')
                .should('have.class', 'error-msg')
                .contains("We're having technical difficulties...")
    })
})