import simpsonsQuoteTest from './simpsonsQuoteData';

describe('Home page flow', ()=> {
    it('Should be able to visist the app and render the correct elements', () => {
        cy.intercept('GET', 'https://thesimpsonsquoteapi.glitch.me/quotes', simpsonsQuoteTest)
        cy.visit('http://localhost:3000/home')
            .contains('Who Said It?')
                .get('img')
                    .should('have.class', 'App-logo')
                .get('nav')
                    .should('have.class', 'navbar')
                    .contains('Woohoo: 0')
                .get('h2')
                    .contains("D'oh: 0")
                .get('h2')
                    .contains('Fav Quotes')
                .get('section')
                    .should('have.class','quote-body')
                .get('div')
                    .should('have.class', 'quote')
                .get('div')
                    .should('have.class', 'top-corner')
                .get('p')
                    .contains("For once maybe someone will call me \"sir\" without adding, \"You're making a scene.\"")
                .get('button')
                    .should('have.class', 'quote-button')
                .get('p')
                    .contains('Click when you know')
                .get('p')
                    .contains('Who Said It')
                .get('img')
                    .should('have.class', 'simpsons-family')
    })
    it("Should be able to display a loading message if the movies data isn't fetched properly", () => {
        cy.intercept('GET', 'https://thesimpsonsquoteapi.glitch.me/quotes', {forceNetworkError: true})
        cy.visit('http://localhost:3000/home')
            .contains('Who Said It?')
                .get('img')
                    .should('have.class', 'App-logo')
                .get('nav')
                    .should('have.class', 'navbar')
                    .contains('Woohoo: 0')
                .get('h2')
                    .contains("D'oh: 0")
                .get('h2')
                    .contains('Fav Quotes')
                .get('section')
                    .should('have.class','quote-body')
                    .contains('Loading...')
    })
})