describe('Home page flow', ()=> {
    it('Should be able to visit the app and render the correct elements with loading message', () => {
        cy.intercept('GET', 'https://thesimpsonsquoteapi.glitch.me/quotes', { fixture: 'mock_data_1.json' })
        cy.visit('http://localhost:3000/')
        cy.contains('Who Said It?')
            .get('img')
                .should('have.class', 'App-logo')
            .get('nav')
                .should('have.class', 'navbar')
                .contains('Woohoo: 0')
            .get('h2')
                .contains("D'oh: 0")
            .get('h2')
                .contains('Fav Quotes')
            .get('section')
                .should('have.class','quote-body')
            .get('div')
                .should('have.class', 'quote')
            .get('div')
                .should('have.class', 'top-corner')
            .get('p')
                .contains('Loading...')               
    })
    it("Should be able to display a loading message if the movies data isn't fetched properly", () => {
        cy.intercept('GET', 'https://thesimpsonsquoteapi.glitch.me/quotes', {forceNetworkError: true})
        cy.visit('http://localhost:3000/')
            .contains('Who Said It?')
                .get('img')
                    .should('have.class', 'App-logo')
                .get('nav')
                    .should('have.class', 'navbar')
                    .contains('Woohoo: 0')
                .get('h2')
                    .contains("D'oh: 0")
                .get('h2')
                    .contains('Fav Quotes')
                .get('section')
                    .should('have.class','quote-body')
                    .contains('Loading...')
                .get('div')
                    .should('have.class', 'error-msg')
                    .contains("We're having technical difficulties...")
    })
})